name: wp-pager

services:
    app:
        image: wp-pager-app
        build:
            context: .
        container_name: wp-pager-app
        restart: always
        ports:
            - 80:8080
        depends_on:
            - db
        networks:
            - database
        volumes:
            - ./wordpress:/var/www/html
            - ./plugin:/var/www/html/wp-content/plugins/wp-pager
            - /var/www/html/wp-content/plugins/wp-pager/vendor
            - /var/www/html/wp-content/plugins/wp-pager/node_modules
        environment:
            WORDPRESS_DB_HOST: pager_db
            WORDPRESS_DB_USER: pager
            WORDPRESS_DB_PASSWORD: 111111
            WORDPRESS_DB_NAME: pager
            WORDPRESS_DEBUG: 1

    db:
        image: mariadb:10.7.3-focal
        command: --default-authentication-plugin=mysql_native_password
        container_name: wp-pager-db
        restart: always
        ports:
            - 2222:3306
        networks:
            - database
        volumes:
            - ./database:/var/lib/mysql
        environment:
            MYSQL_DATABASE: pager
            MYSQL_USER: pager
            MYSQL_PASSWORD: 111111
            MYSQL_ROOT_PASSWORD: 111111

networks:
    database:
        driver: bridge