name: Copy plugin directory to plugin branch

on:
    push:
        branches: [master]

permissions: write-all

jobs:
    copy:
        runs-on: ubuntu-latest
        steps:
            # Checkout into my repo locally
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Fetch the entire Git history

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '24'

            - name: Install and build assets
              run: |
                  cd plugin
                  npm install
                  npm run prod

            # Checkout into my repo locally
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Fetch the entire Git history
                  ref: plugin # Choose branch

            - name: Set git user
              run: |
                  git config user.name "${{ github.actor }}"
                  git config user.email "${{ github.actor }}@users.noreply.github.com"
                  sudo chown -R $USER:$USER .

            - name: Move plugin files to the plugin branch
              run: |
                  git checkout -p origin/master -- build/*
                  git commit -m "ci: Move files from `plugin` to `plugin` branch"
                  git push origin plugin
