name: copy-to-plugin-branch

on:
    push:
        branches:
            - master

jobs:
    mirror-to-binder:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install and build assets
              run: |
                  cd plugin
                  npm install
                  npm run prod

            - name: Install dependencies
              uses: php-actions/composer@v6
              with:
                php_version: "8.1"
                working-directory: ./plugin
                command: install --no-dev --no-interaction

            - uses: tuftsrt/copy-to-branch@v1
              with:
                  destination-branch: plugin
                  clear-destination: 'true'
                  copy: |
                      plugin/*|
