name: copy-to-plugin-branch

on:
    push:
        branches:
            - master

jobs:
    mirror-to-binder:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - id: date
              run: |
                  echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
            - uses: tuftsrt/copy-to-branch@v1
              with:
                  destination-branch: binder
                  clear-destination: 'true'
                  copy: |
                      plugin/*|
